version: '3'
services:
  app:
    build: .
    volumes:
      - ./app.py:/app/app.py
      - ./data:/app/data
      - ./models:/app/models
      - ./static:/app/static
      - ./templates:/app/templates
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - "5432:5432"